### ISSUE TITLE
教你编译调试Elasticsearch 6.3.2源码 | 小旋锋

### ISSUE THREAD

**Issue by whirlys** [whirlys/whirlys.github.io#11]
http://laijianfeng.org/2018/08/%E6%95%99%E4%BD%A0%E7%BC%96%E8%AF%91%E8%B0%83%E8%AF%95Elasticsearch-6-3-2%E6%BA%90%E7%A0%81/

**Comment by chasuner** [comment]
赞，靠谱！开源项目搞环境真的是太麻烦了，以后开源的项目应该改进的更友好点
